"""empty message

Revision ID: 52bdfc097d15
Revises: 4c85fdd097ad
Create Date: 2022-06-16 17:14:49.941196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52bdfc097d15'
down_revision = '4c85fdd097ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pins', sa.Column('image_file', sa.String(length=40), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pins', 'image_file')
    # ### end Alembic commands ###
