"""empty message

Revision ID: 60697ddeb01f
Revises: 7af7296fcada
Create Date: 2022-06-27 18:58:23.800866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60697ddeb01f'
down_revision = '7af7296fcada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pin_id'], ['pins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    # ### end Alembic commands ###
