"""empty message

Revision ID: 7af7296fcada
Revises: d24919c4ec6c
Create Date: 2022-06-23 11:22:54.396989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7af7296fcada'
down_revision = 'd24919c4ec6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board_of_pins', sa.Column('pinboard_id', sa.Integer(), nullable=False))
    op.alter_column('board_of_pins', 'pin_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('board_of_pins_pin_id_fkey', 'board_of_pins', type_='foreignkey')
    op.drop_constraint('board_of_pins_board_id_fkey', 'board_of_pins', type_='foreignkey')
    op.create_foreign_key(None, 'board_of_pins', 'pinboard', ['pinboard_id'], ['id'])
    op.create_foreign_key(None, 'board_of_pins', 'pins', ['pin_id'], ['id'])
    op.drop_column('board_of_pins', 'board_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board_of_pins', sa.Column('board_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'board_of_pins', type_='foreignkey')
    op.drop_constraint(None, 'board_of_pins', type_='foreignkey')
    op.create_foreign_key('board_of_pins_board_id_fkey', 'board_of_pins', 'pinboard', ['board_id'], ['id'])
    op.create_foreign_key('board_of_pins_pin_id_fkey', 'board_of_pins', 'user', ['pin_id'], ['id'])
    op.alter_column('board_of_pins', 'pin_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('board_of_pins', 'pinboard_id')
    # ### end Alembic commands ###
