"""empty message

Revision ID: 8909dafb4148
Revises: c2f88cad89a7
Create Date: 2022-07-05 16:30:14.321935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8909dafb4148'
down_revision = 'c2f88cad89a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pins', 'is_notification_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pins', sa.Column('is_notification_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
