"""empty message

Revision ID: d24919c4ec6c
Revises: 6d2bc59d2974
Create Date: 2022-06-22 17:25:37.890521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd24919c4ec6c'
down_revision = '6d2bc59d2974'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_of_pins',
    sa.Column('pin_id', sa.Integer(), nullable=True),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['pinboard.id'], ),
    sa.ForeignKeyConstraint(['pin_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('board_of_pins')
    # ### end Alembic commands ###
