"""empty message

Revision ID: f917619c0cf2
Revises: 22cd4bd400fd
Create Date: 2022-06-22 10:58:03.060469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f917619c0cf2'
down_revision = '22cd4bd400fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pinboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_name', sa.String(length=80), nullable=False),
    sa.Column('board_is_private', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pinboard')
    # ### end Alembic commands ###
